name: Terraform Cloud Deployment

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "Ayodev"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "demo"
  CONFIG_DIRECTORY: "./"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Terraform Cloud
      run: echo -n ${{ secrets.TF_API_TOKEN }} > ~/.terraformrc && chmod 600 ~/.terraformrc

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve tfplan
